#!/bin/bash --login

# PBS job options (name, compute nodes, job time)
#PBS -N __performance_out
#PBS -l select=2:ncpus=36
#PBS -l walltime=24:00:00
#PBS -A d171-s2000901
#PBS -l place=excl
#PBS -j oe

# Change to the directory that the job was submitted from
# (remember this should be on the /work filesystem)
#cd $PBS_O_WORKDIR

echo processes,l,time
for p in 1 2 4 8 16 32 64; do
  for l in 250 500 750 1000; do
    for s in 1 2 3 4 5 6 7 8 9 10; do
      mpiexec_mpt -perhost 32 -n $p ./percolate_par $s -l $l \
      | sed 's/ //g'
    done
  done
done
